name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
  workflow_dispatch:

jobs:
  spotless:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: spotless check
        run: |
          chmod +x gradlew
          ./gradlew spotlessCheck

  build_discord_bot:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: build discord-bot
        run: |
          chmod +x gradlew
          ./gradlew discord-bot:build

  build_database_lib:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: build database-lib
        run: |
          chmod +x gradlew
          ./gradlew database-lib:build

  build_tba_api:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: build tba-api
        run: |
          chmod +x gradlew
          ./gradlew tba-api:build

  build_all:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: build all
        run: |
          chmod +x gradlew
          ./gradlew build