name: CI/CD

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  docker_multi_arch_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: set up docker engine
        # https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04
        run: |
          sudo apt update
          sudo apt install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          sudo apt install docker-ce -y

      - name: build project
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: docker build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./discord-bot
          push: true
          platforms: |
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64
          tags: |
            ghcr.io/tigerbotics7125/discord-bot:${{ github.event.release.tag_name }}
            ghcr.io/tigerbotics7125/discord-bot:latest